version: '3'

services:

  db:
    container_name: menuexample-db
    image: postgres:10
    restart: "always"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    ports:
    - 5432:5432
    networks:
      - menuexample

  django:
    container_name: menuexample
    image: menuexample:latest
    build:
      context: .
      dockerfile: Dockerfile.django
    restart: "always"
    command: ["bash", "django.sh"]
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./src:/app
      - static:/files/static
      - media:/files/media
    depends_on:
      - db
    links:
      - db:database
    networks:
      - menuexample

  nginx:
    container_name: menuexample-nginx
    image: nginx:latest
    restart: "always"
    command: ['nginx', '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - ${PORT}:80
    depends_on:
      - django
    networks:
      - menuexample


volumes:
  db:
  static:
  media:

networks:
  menuexample: